### ISSUE TITLE
Feature request: Alive light

### ISSUE THREAD

**Issue by mikilbc** [vinz486/fingerprint-r503-mqtt#2]
Can you add a light (breathing ring of fingerprint reader or some Wemos D1 pin) to indicate live communication with MQTT server?
This can be useful to identify, that whole system is ready (for finger).
If this is not possible, can you add MQTT "command" for light on/off?

BTW: Thanks for good work and specially for updating readme.

**Comment by vinz486** [comment]
Hi,
yes, this is interesting.

I will try to make onboard led blink/on when connection is ok.

**Comment by vinz486** [comment]
Added connection signalling in the last commit. From readme:

"Onboard blue led will signal when connection to MQTT broker is established: solid when connected, blink when connecting. Signalling is referred to MQTT, so even if network connection is ok but MQTT is broken the led will blink."

**Comment by bad-gargoyle** [comment]
In my case my R503 senson, even if it is connected to MQTT broker, does not signal connection status. Should I enable something in project before uploading?
